### ISSUE TITLE
Dynamic Functioning

### ISSUE THREAD

**Issue by abirbhattacharya82** [abirbhattacharya82/Basic-Calculator#1]
# Dynamic Functioning
The Calculator gives the correct answer only when "=" is pressed
Try to provide correct results everytime a new operand is entered even though the "=" is not pressed.
The final result should be shown with a greater font once "=" is pressed.
#### Have a Nice Day. And Happy Coding.

**Comment by SOH28** [comment]
hey I have made it but it has got one issue....when u press any operand the display number gets converted into double format
Ex: I want to make a calc 5x6. When I press x operand the display shows 5.00x_6_
